spring:
  profiles:
    active: localhost
---
spring:
  profiles: localhost
  application:
    name: example-user
    
server:
  port: 8080

logging:
  level:
    yongs:
      temp: DEBUG

app:
  datasource:
    jdbc-url: jdbc:mariadb://localhost:3306/temp
    driverClassName: org.mariadb.jdbc.Driver
    username: scott
    password: tiger
    maximum-pool-size: 5

eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
    instanceId: ${spring.application.name}:${random.value}
  client:
    registerWithEureka: true
    fetchRegistry: true
    enabled: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
      
---
spring:
  profiles: docker
  application:
    name: example-user
    
server:
  port: 8080

logging:
  level:
    yongs:
      temp: INFO

app:
  datasource:
    # docker 컨테이너로 실행되므로 maria-db로 접근이 가능하지만
    # gradle test를 docker 컨테이너에서 수행하면   maria-db로 접근
    # gradle test를 docker 컨테이너가 아닌 node에서 수행할 경우에서 db ip를 명시해 줘야 한다. 
    jdbc-url: jdbc:mariadb://maria-db:3306/temp
    driverClassName: org.mariadb.jdbc.Driver
    username: scott
    password: tiger
    maximum-pool-size: 10
                         
eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-server
  client:
    registerWithEureka: true 
    fetchRegistry: true
    enabled: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
            